version: "3.7"

services:
  server:
    image: lv-client-customer
    ports:
      - "80:5000"
    env_file:
      - ./.env
    environment:
      - API_URL=http://3.26.55.185:3008
      - SOCKET_URI=http://3.26.55.185:8080
    stdin_open: true
    tty: true

